In [1]:
print('Visão Computacional e Aprendizado de Máquina')

Visão Computacional e Aprendizado de Máquina


In [6]:
lst_1 = ['Janeiro', 'Fevereiro', 'Março']

In [7]:
lst_1

['Janeiro', 'Fevereiro', 'Março']

In [8]:
x = 0
s = 0
while x < 25:
    s = s + x
    x = x + 1
    print('Valor de X: ', x, 'Valor de S: ', s)

Valor de X:  1 Valor de S:  0
Valor de X:  2 Valor de S:  1
Valor de X:  3 Valor de S:  3
Valor de X:  4 Valor de S:  6
Valor de X:  5 Valor de S:  10
Valor de X:  6 Valor de S:  15
Valor de X:  7 Valor de S:  21
Valor de X:  8 Valor de S:  28
Valor de X:  9 Valor de S:  36
Valor de X:  10 Valor de S:  45
Valor de X:  11 Valor de S:  55
Valor de X:  12 Valor de S:  66
Valor de X:  13 Valor de S:  78
Valor de X:  14 Valor de S:  91
Valor de X:  15 Valor de S:  105
Valor de X:  16 Valor de S:  120
Valor de X:  17 Valor de S:  136
Valor de X:  18 Valor de S:  153
Valor de X:  19 Valor de S:  171
Valor de X:  20 Valor de S:  190
Valor de X:  21 Valor de S:  210
Valor de X:  22 Valor de S:  231
Valor de X:  23 Valor de S:  253
Valor de X:  24 Valor de S:  276
Valor de X:  25 Valor de S:  300


In [9]:
nome = 'Harley'

In [12]:
nome += ' Silva'

In [13]:
nome

'HarleySilva Silva'

In [14]:
lst_1 += ['Abril']

In [15]:
lst_1

['Janeiro', 'Fevereiro', 'Março', 'Abril']

In [16]:
lst_1 += 'Maio'

In [17]:
lst_1

['Janeiro', 'Fevereiro', 'Março', 'Abril', 'M', 'a', 'i', 'o']

In [23]:
lst_1.remove('o')

In [24]:
lst_1

['Janeiro', 'Fevereiro', 'Março', 'Abril', 'M', 'a', 'i']

In [26]:
lst_1.remove('M')

In [27]:
lst_1.remove('a')

In [28]:
lst_1.remove('i')

In [29]:
lst_1

['Janeiro', 'Fevereiro', 'Março', 'Abril']

In [30]:
v_str = 'Visão Computacional'

In [32]:
v_str [::-1]

'lanoicatupmoC oãsiV'

In [33]:
print('Aluno: ', nome, ' cursou a disciplina: ', v_str, ' em ', lst_1[3])

Aluno:  HarleySilva Silva  cursou a disciplina:  Visão Computacional  em  Abril


In [34]:
def media_notas(lista):
    return sum(lista)/len(lista)

In [48]:
ent = 0.
lst_notas = []
while True:
    ent = float(input('Digite uma nota ou Q para parar: '))
    if ent == "Q":
        break
    elif ent.isnumeric():
        lst_notas.append(float(ent))
media = media_notas(lst_notas)
lst_notas.sort()
print('A média é: ', round(media,2))
print('Quantidade de elementos: ', len(lst_notas))
print('Menor valor: ', lst_notas[0])
print('Maior valor: ', lst_notas[-1])

Digite uma nota ou Q para parar:  5.5


AttributeError: 'float' object has no attribute 'isnumeric'

In [46]:
lst_notas.sort?

Signature: lst_notas.sort(*, key=None, reverse=False)
Docstring:
Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them,
ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.
Type:      builtin_function_or_method

In [41]:
lst_notas.clear()

In [42]:
lst_notas

[]

In [44]:
len(lst_notas)

4

In [45]:
media

7.25

## Numpy

In [59]:
import numpy as np


In [60]:
np.__version__

'1.26.4'

In [61]:
m1 = np.array([12, 3, 5, 7, -6, 0])
m2 = np.array([6, 12, 7, 11, 5, 1])

In [62]:
m1 + m2

array([18, 15, 12, 18, -1,  1])

In [63]:
m1 * m2

array([ 72,  36,  35,  77, -30,   0])

In [64]:
print([n*n for n in range(1000)])

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956, 18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449, 20736, 21025, 21316, 21609, 21904, 22201, 22500, 22801, 23104, 23409, 23716, 24025, 24336, 24649, 24964, 25281, 25600, 25921, 26244, 2656

In [65]:
m1 = [n for n in range(1000)]
m2 = [n for n in range(1000)]

In [68]:
def dot(m1, m2):
    s = 0
    for i in range(1000):
        s += m1[i] * m2[i]
    return s

In [69]:
%timeit dot(m1, m2)

105 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [70]:
%timeit np.dot(m1,m2)

90.8 µs ± 198 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [71]:
m0 = np.array([[0,1,2], [4,5,6]])

In [72]:
m0

array([[0, 1, 2],
       [4, 5, 6]])

In [73]:
m0.shape

(2, 3)

In [76]:
m0.reshape(3, 2)

array([[0, 1],
       [2, 4],
       [5, 6]])

In [77]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])